### ISSUE TITLE
Bazel Build Failed

### ISSUE THREAD

**Issue by jiangwenhan** [stardog-union/rocksdb#7]
Is the master branch can build use bazel successfully? 
I try to run command "bazel build ...", but it failed, fail on org_lz4.

**Comment by matthewvon** [comment]
Stardog's bazel files are currently customized to our bigger product build.  That build includes org_lz4 as an outside build library.  We have plans to move the the bazel build maintained by Facebook for RocksDB in the future.  But that is a few months away.

The quickest solution for you is to revert to Facebook's cmake build of rocksdb.  My apologies.
